spring:
  datasource:
    url: jdbc:mysql://localhost:3307/IODB?serverTimezone=GMT-3
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql : true
    hibernate:
      ddl-auto: none
    database: mysql

